### ISSUE TITLE
some carla   traffic manager problems

### ISSUE THREAD

**Issue by hexrefugee** [CLaSLoVe/Carla-lidar-data-generator#1]
Hi,
Your Carla-lidar-data-generator is so great, I learn a lot from it.
And, I met some problems in using traffic manager tools.
I want to spawn 30 vehicles without sensors, and I used carla PythonAPI/example/generate_traffic.py
and I also want to spawn one vehicle with lidar.
but when I run this two python scripts. The carla-server run wierd. Some vehicles run around.
It is the tm settings problems?

**Comment by CLaSLoVe** [comment]
In theory, it should be possible to run multiple TM scripts simultaneously. You can try referring to my script and running them in sequence. Can you provide more information?

**Comment by hexrefugee** [comment]
Yes, I refer to your script :
server_setup.py
generate_traffic.py
and I find in server_setup.py, you set 
...
settings.synchronous_mode = True
traffic_manager.set_synchronous_mode(True)
...
and in generate_traffic.py, you are not set settings.synchronous_mode  and traffic_manager.set_synchronous_mode
is this covered?

For my problem, I run your code server_setup.py first, and run generate_traffic.py, and run my own spawn ego_vehicle with lidar in sync mode. It works relatively smooth. I'm little confuse... 
Thank for your reply.

> In theory, it should be possible to run multiple TM scripts simultaneously. You can try referring to my script and running them in sequence. Can you provide more information?

**Comment by CLaSLoVe** [comment]
In my opinion, the configuration for tm should be done in one go, multiple attempts may cause issues. You may refer to https://carla.readthedocs.io/en/latest/adv_traffic_manager/ for guidance.

**Comment by CLaSLoVe** [comment]
My code is based on earlier versions of Carla (prior to 2022.8), and I'm not sure if there have been any changes in the current version of Carla. 
Furthermore, I have discovered some bugs in Carla in the version I am using. For instance, cyclists have a chance of having a width of 0, and there is a lag in the bbox position. Since I haven't worked on this project recently, I am not sure if these issues have been fixed. However, you can keep these issues in mind while building your script.

**Comment by hexrefugee** [comment]
多谢回复，对的，我仔细参考了官网关于tm的文档，所以就感觉很迷惑。而且在generate中发现设置的是同步后，
372行
White True:
   world.wait_for_tick()
这个居然可以跑通？我在我的写的生成交通流里面设置同步然后使用 world.wait_for_tick()就直接卡死了
┭┮﹏┭┮


> In my opinion, the configuration for tm should be done in one go, multiple attempts may cause issues. You may refer to https://carla.readthedocs.io/en/latest/adv_traffic_manager/ for guidance.

**Comment by CLaSLoVe** [comment]
你是不是多次设置了tm导致了问题？carla应该是构建了多个进程然后通过之间的通讯完成的。你的卡死我感觉应该是设置的问题。
不过carla确实很卡，我当时跑大量数据集，时间长了会卡死。

**Comment by hexrefugee** [comment]
> 你是不是多次设置了tm导致了问题？carla应该是构建了多个进程然后通过之间的通讯完成的。你的卡死我感觉应该是设置的问题。 不过carla确实很卡，我当时跑大量数据集，时间长了会卡死。

我是在自己的生成交通流脚本里面设置同步，然后在while true里面使用wait_for_tick()就直接卡死了，但你的源码里面运行确实正常的。。。
然后之前的多个tm是因为，原来的设想是三个脚本，一个生成交通流的脚本，另一个是生成一辆带有激光雷达的车，另一个是在路侧架设了一个激光雷达的脚本，后面两个是使用了ros改的。然后就需要联合仿真，但是三个一起跑的时候，就会发现交通流的车辆会瞎跑。。。然后就在寻找解决方法。然后就看到了官网上面关于多个client的tm设置，最后设置了车辆还是到处瞎跑。最后就看到了你的开源的代码，然后就clone下来，和后面两个脚本联合跑了下，发现车辆没有瞎跑的情况了。+1+1+1
ps：大佬方便给个邮箱吗？

**Comment by CLaSLoVe** [comment]
哈哈解决了就好，这个项目是我去年暑期实习给别的课题组写的，我现在已经不搞这个项目啦~
